apiVersion: v1
data:
  pod: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: entando-jx-maven-java11
      labels:
        jenkins.io/kind: build-pod
      annotations:
        jenkins-x.io/devpodPorts: 5005, 8080
    spec:
      serviceAccount: jenkins
      nodeSelector:
      volumes:
      - name: workspace-volume
        emptyDir: {}
      - name: docker-daemon
        hostPath:
          path: /var/run/docker.sock
      - name: volume-0
        secret:
          secretName: jenkins-maven-settings
      - name: volume-1
        secret:
          secretName: jenkins-docker-cfg
      - name: volume-2
        secret:
          secretName: jenkins-release-gpg
      containers:
      - name: maven
        image: docker-registry.default.svc.cluster.local:5000/entando/entando-jx-maven-java11:0.0.16
        args:
        - cat
        command:
        - /bin/sh
        - -c
        workingDir: /home/jenkins
        securityContext:
          privileged: true
        tty: true
        env:
        - name: SONAR_TOKEN
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: sonar.token
        - name: SONAR_GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: sonar.github.token
        - name: OWASPDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: owaspdb.username
        - name: OWASPDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: owaspdb.password
        - name: OWASPDB_URL
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: owaspdb.url
        - name: GPG_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: gpg.passphrase
        - name: GPG_KEYNAME
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: gpg.keyname
        - name: GPG_HOMEDIR
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: gpg.homedir
        - name: EXECUTABLE_TYPE
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: executable.type
        - name: ENTANDO_DEFAULT_ROUTING_SUFFIX
          valueFrom:
            secretKeyRef:
              name: entando-jx-common-secret
              key: default.routing.suffix
        - name: DOCKER_REGISTRY
          valueFrom:
            configMapKeyRef:
              name: jenkins-x-docker-registry
              key: docker.registry
        - name: DOCKER_CONFIG
          value: /home/jenkins/.docker/
        - name: GIT_AUTHOR_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_NAME
          value: jenkins-x-bot
        - name: GIT_COMMITTER_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_COMMITTER_NAME
          value: jenkins-x-bot
        - name: JENKINS_URL
          value: http://jenkins:8080
        - name: MAVEN_OPTS
          value: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        - name: XDG_CONFIG_HOME
          value: /home/jenkins
        - name: _JAVA_OPTIONS
          value: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx8000m
        resources:
          requests:
            cpu: 400m
            memory: 2Gi
          limits:
            cpu: 8
            memory: 12Gi
        volumeMounts:
          - mountPath: /home/jenkins
            name: workspace-volume
          - name: docker-daemon
            mountPath: /var/run/docker.sock
          - name: volume-0
            mountPath: /root/.m2/
          - name: volume-1
            mountPath: /home/jenkins/.docker
          - name: volume-2
            mountPath: /home/jenkins/.gnupg
kind: ConfigMap
metadata:
  annotations:
    jenkins.io/chart: env
  labels:
    jenkins.io/chart-release: jenkins-x
    jenkins.io/kind: podTemplate
    jenkins.io/namespace: jx
    jenkins.io/version: 2.0.1865
  name: jenkins-x-pod-template-entando-jx-maven-java11

